import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-input',
  template: `
    <p>
      input Works!
    </p>


<input [value]="title" 
         (keyup.enter)="changeTitle($event.target.value)" 
         #inputElement> 

<button (click)="changeTitle(inputElement.value)"> 
Save
</button>
<br>
<br>
<br>

<p>The title is: {{ title }}</p>
  `,
  styleUrls: ['./input.component.css']
})
export class InputComponent implements OnInit {

  private title: string = '';
  constructor() { 
    //console.log('in constructor');
    //this.changeTitle('I love Angular');
    //console.log(this.title);
  }

changeTitle(inputElementReference): void {
  console.log(inputElementReference);
  this.title = inputElementReference.value;
              
}

  ngOnInit() {
  //this.title = 'Hello World 123';
  //this.changeTitle("Seufz")
  //setTimeout(() => {
  //  this.title = 'This is not the title you are looking for';  
  //}, 3000);
  //}
  //generateTitle(): string {
  //return 'This title was generated by a method.';
}

}